[package]
name = "task-tun"
version = "0.1.0"
edition = "2021"

[dependencies]
mio = { version = "1.0", features = ["net", "os-poll", "os-ext"] }
tun = "0.7"
clap = { version = "4.5.54", features = ["derive"] }
etherparse = "0.14"